[package]
name = "zepto"
version = "0.0.2"
authors = ["senees <code@senees.de>"]
description = "zepto"
documentation = "https://docs.rs/zepto"
repository = "https://github.com/senees/zepto.git"
license = "MIT"
edition = "2021"